import type { SearchResult } from "@/types";

/**
 * Isolated mock data for Phase 3 search results.
 * Replace this with real API calls in Phase 4 by swapping
 * the functions below to use services/api.ts instead.
 */

export const MOCK_SEARCH_RESULTS: SearchResult[] = [
  // ── EXACT MATCHES ──────────────────────────────────────────────
  {
    id: "res-1",
    matchType: "EXACT",
    pharmacyId: "ph-1",
    pharmacyName: "Grace Pharmacy",
    verified: true,
    distanceKm: 1.2,
    isOpen: true,
    address: "12 Oluwo Road, Ile-Ife",
    medicineId: "med-1",
    medicineName: "Amoxicillin 500mg Capsules",
    genericName: "Amoxicillin",
    brand: "Emzor",
    strength: "500mg",
    dosageForm: "Capsule",
    activeIngredient: "Amoxicillin Trihydrate",
    requiresPrescription: true,
    price: 2500,
    quantity: 18,
    stockStatus: "IN_STOCK",
    freshness: "LIVE",
    lastUpdated: "2026-09-21T18:47:00+01:00",
    updateMethod: "API_SYNC",
  },
  {
    id: "res-2",
    matchType: "EXACT",
    pharmacyId: "ph-2",
    pharmacyName: "HealthPlus Pharmacy",
    verified: true,
    distanceKm: 2.1,
    isOpen: true,
    address: "Oduduwa Way, Ile-Ife",
    medicineId: "med-1",
    medicineName: "Amoxicillin 500mg Capsules",
    genericName: "Amoxicillin",
    brand: "Emzor",
    strength: "500mg",
    dosageForm: "Capsule",
    activeIngredient: "Amoxicillin Trihydrate",
    requiresPrescription: true,
    price: 2800,
    quantity: 5,
    stockStatus: "LOW_STOCK",
    freshness: "FRESH",
    lastUpdated: "2026-09-21T17:24:00+01:00",
    updateMethod: "MANUAL_UPDATE",
  },
  {
    id: "res-3",
    matchType: "EXACT",
    pharmacyId: "ph-3",
    pharmacyName: "Alpha Pharma",
    verified: false,
    distanceKm: 3.4,
    isOpen: false,
    address: "Lagere, Ile-Ife",
    medicineId: "med-1",
    medicineName: "Amoxicillin 500mg Capsules",
    genericName: "Amoxicillin",
    brand: "Emzor",
    strength: "500mg",
    dosageForm: "Capsule",
    activeIngredient: "Amoxicillin Trihydrate",
    requiresPrescription: true,
    price: 2200,
    quantity: 40,
    stockStatus: "IN_STOCK",
    freshness: "RECENT",
    lastUpdated: "2026-09-21T10:00:00+01:00",
    updateMethod: "PHARMACY_CONFIRM",
  },
  {
    id: "res-4",
    matchType: "EXACT",
    pharmacyId: "ph-4",
    pharmacyName: "Medifield Pharmacy",
    verified: true,
    distanceKm: 4.8,
    isOpen: true,
    address: "OAU Teaching Hospital Road, Ile-Ife",
    medicineId: "med-1",
    medicineName: "Amoxicillin 500mg Capsules",
    genericName: "Amoxicillin",
    brand: "Emzor",
    strength: "500mg",
    dosageForm: "Capsule",
    activeIngredient: "Amoxicillin Trihydrate",
    requiresPrescription: true,
    price: 3000,
    quantity: 40,
    stockStatus: "IN_STOCK",
    freshness: "OLD",
    lastUpdated: "2026-09-20T16:32:00+01:00",
    updateMethod: "MANUAL_UPDATE",
  },
  {
    id: "res-5",
    matchType: "EXACT",
    pharmacyId: "ph-5",
    pharmacyName: "RxPoint Pharmacy",
    verified: true,
    distanceKm: 5.5,
    isOpen: true,
    address: "Stadium Area, Ile-Ife",
    medicineId: "med-1",
    medicineName: "Amoxicillin 500mg Capsules",
    genericName: "Amoxicillin",
    brand: "Emzor",
    strength: "500mg",
    dosageForm: "Capsule",
    activeIngredient: "Amoxicillin Trihydrate",
    requiresPrescription: true,
    price: 2600,
    quantity: 0,
    stockStatus: "OUT_OF_STOCK",
    freshness: "FRESH",
    lastUpdated: "2026-09-21T15:10:00+01:00",
    updateMethod: "MANUAL_UPDATE",
  },

  // ── RELATED PRODUCTS ──────────────────────────────────────────
  {
    id: "res-6",
    matchType: "RELATED",
    pharmacyId: "ph-1",
    pharmacyName: "Grace Pharmacy",
    verified: true,
    distanceKm: 1.2,
    isOpen: true,
    address: "12 Oluwo Road, Ile-Ife",
    medicineId: "med-2",
    medicineName: "Amoxicillin 500mg Capsules",
    genericName: "Amoxicillin",
    brand: "M&B",
    strength: "500mg",
    dosageForm: "Capsule",
    activeIngredient: "Amoxicillin Trihydrate",
    requiresPrescription: true,
    price: 2100,
    quantity: 25,
    stockStatus: "IN_STOCK",
    freshness: "LIVE",
    lastUpdated: "2026-09-21T18:47:00+01:00",
    updateMethod: "API_SYNC",
  },
  {
    id: "res-7",
    matchType: "RELATED",
    pharmacyId: "ph-6",
    pharmacyName: "Obanla Pharmacy",
    verified: false,
    distanceKm: 2.7,
    isOpen: true,
    address: "Obanla Junction, Ile-Ife",
    medicineId: "med-3",
    medicineName: "Amoxicillin 500mg Capsules",
    genericName: "Amoxicillin",
    brand: "Bayer",
    strength: "500mg",
    dosageForm: "Capsule",
    activeIngredient: "Amoxicillin Trihydrate",
    requiresPrescription: true,
    price: 3200,
    quantity: 10,
    stockStatus: "LOW_STOCK",
    freshness: "RECENT",
    lastUpdated: "2026-09-21T09:00:00+01:00",
    updateMethod: "PHARMACY_CONFIRM",
  },
];

/**
 * Simulates fetching search results.
 * Replace with `api.get<SearchResult[]>(...)` in Phase 4.
 */
export function getMockSearchResults(_query: string, _location: string): SearchResult[] {
  // In a real implementation, filter by query and location here.
  return MOCK_SEARCH_RESULTS;
}
